### ISSUE TITLE
IDE Support

### ISSUE THREAD

**Issue by kkolyan** [davidpdrsn/extend#24] opened 2021-10-04 18:59 UTC
All works, but at the same time IDEA (using official Rust plugin) marks all usages of red with `Cannot define inherent `impl` for a type outside of the crate where the type is defined [E0116]`.

I guess that's known issue, but I wonder if there are any perspective to improve this aspect.

**Comment by davidpdrsn** [comment] 2021-10-04 19:04
I'm not aware of any such issues. Can you provide a reproduction script?

**Comment by kkolyan** [comment] 2021-10-04 22:52
1. install `Intellij IDEA Ultimate` (Community doesn't support Rust plugin) or `JetBrains CLion`.
2. install [Rust plugin](https://plugins.jetbrains.com/plugin/8182-rust) via `Settings/Plugins`/
3. create new project and replace `main.rs` with main example of this library ([extend_hello.zip](https://github.com/davidpdrsn/extend/files/7281691/extend_hello.zip))

### Expected
IDE shows no errors
### Actual
![image](https://user-images.githubusercontent.com/3194236/135934383-56020d98-c313-4542-a6c3-7fddd1ff6ff8.png)

**Comment by davidpdrsn** [comment] 2021-10-05 05:47
That's gotta be a bug in the Intellij plug-in. Rust analyzer handles it just fine. I suggest you file an issue there. It's probably just that they don't expand attribute macros. RA didn't do that either until recently.

In general if something is accepted by rustc but not the IDE plug-in then it's probably the plug-in that is at fault.

**Comment by kkolyan** [comment] 2021-10-05 14:59
yeah, that is known JB's issue with workaround: https://github.com/intellij-rust/intellij-rust/issues/6908

**Comment by davidpdrsn** [comment] 2021-10-05 15:10
Alright. I'll close this issue for now then since there is nothing we can do from here.

**Closed as completed by davidpdrsn** 2021-10-05 15:10 UTC

**Comment by fzyzcjy** [comment] 2021-10-22 03:40
I have the same issue. @kkolyan May I know which workaround do you use? That issue seems to be open.

**Comment by kkolyan** [comment] 2021-10-22 11:16
@fzyzcjy I just followed first the first 3 steps on this page: intellij-rust/intellij-rust#6908.

**Comment by fzyzcjy** [comment] 2021-10-22 11:56
Thanks!
